name: animated_list
description: A Flutter ListView that implicitly animates between the changes of two lists with the \
  support to reorder its items.
version: 0.4.2
homepage: https://github.com/vaetas/animated_list

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

